//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\Projects\Petroglyph\StringEditor\StringEditor.en.rc
//
#define IDR_MENU1                       101
#define IDS_ERROR_FILE_READ             101
#define IDD_MAINDIALOG                  102
#define IDS_ERROR_FILE_WRITE            102
#define IDD_VERSION_INFO                103
#define IDS_ERROR_FILE_FIND             103
#define IDS_ERROR_FILE_CORRUPT          104
#define IDS_ERROR_FILE_VERSION          105
#define IDD_LANG_SELECT                 106
#define IDS_CURRENT_VERSION             106
#define IDD_IMPORT_NAME                 107
#define IDS_NEW_STRING                  107
#define IDD_NEWFILE                     108
#define IDS_FILES_VDF                   108
#define IDS_FILES_ALL                   109
#define IDR_ACCELERATOR1                110
#define IDS_ERROR_FILE_OPEN             110
#define IDD_EXPORT                      111
#define IDS_ERROR_FILE_SAVE             111
#define IDD_EDITLISTENTRY               112
#define IDS_INFO_NO_CHANGES             112
#define IDS_TITLE_NO_CHANGES            113
#define IDS_FILES_DAT                   114
#define IDD_FIND                        115
#define IDS_ERROR_FILE_IMPORT           115
#define IDD_IMPORT_INDEX                116
#define IDS_ERROR_INVALID_NAMES         116
#define IDS_ERROR_FILE_EXPORT           117
#define IDD_FILE_INFO                   118
#define IDS_INFO_EXPORT_COMPLETE        118
#define IDS_INFORMATION                 119
#define IDS_QUERY_SAVE_CHANGES          120
#define IDS_TITLE_SAVE_CHANGES          121
#define IDS_CONFIRM_LANGUAGE_DELETE     122
#define IDS_CONFIRM                     123
#define IDS_ERROR_TEXT_NOT_FOUND        124
#define IDS_COLUMN_NAME                 125
#define IDS_COLUMN_VALUE                126
#define IDS_COLUMN_COMMENT              127
#define IDS_COLUMN_DATE                 128
#define IDS_COLUMN_LAST_MODIFIED        129
#define IDS_LABEL_VERSION               130
#define IDS_LABEL_LANGUAGE              131
#define IDS_ERROR_UI_INITIALIZATION     132
#define IDS_TOOLTIP_NEW                 133
#define IDS_TOOLTIP_OPEN                134
#define IDS_TOOLTIP_SAVE                135
#define IDS_TOOLTIP_FIND                136
#define IDS_TOOLTIP_CUT                 137
#define IDS_TOOLTIP_COPY                138
#define IDS_TOOLTIP_PASTE               139
#define IDS_TOOLTIP_MOVEUP              140
#define IDS_TOOLTIP_MOVEDOWN            141
#define IDS_TOOLTIP_FINDNEXTINVALID     142
#define IDS_LANGUAGE_ADD                143
#define IDS_LANGUAGE_CHANGE             144
#define IDS_ERROR_EXPORT_POSTFIX        145
#define IDS_ERROR_EXPORT_SELECT         146
#define IDS_FILEINFO_COLUMN_SAVED       147
#define IDS_FILEINFO_COLUMN_AUTHOR      148
#define IDS_FILEINFO_COLUMN_NOTES       149
#define IDS_FILEINFO_NAME_INDEXED       150
#define IDS_FILEINFO_INDEX_INDEXED      151
#define IDS_ERROR_WINDOW_CREATE         152
#define IDS_ERROR_FILE_CREATE           153
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_LIST1                       1003
#define IDC_EDIT3                       1004
#define IDC_GROUP2                      1006
#define IDC_GROUP1                      1007
#define IDC_VERSION                     1008
#define IDC_COMBO1                      1009
#define IDC_STATIC1                     1013
#define IDC_RADIO1                      1014
#define IDC_STATIC8                     1014
#define IDC_RADIO2                      1015
#define IDC_RADIO3                      1017
#define IDC_CHECK1                      1019
#define IDC_RADIO4                      1020
#define IDC_STATIC6                     1020
#define IDC_LIST2                       1021
#define IDC_LIST3                       1022
#define IDC_STATIC2                     1023
#define IDC_STATIC3                     1024
#define IDC_STATIC4                     1025
#define IDC_BUTTON1                     1027
#define IDC_EDITLIST1                   1028
#define IDC_BUTTON2                     1029
#define IDC_CHECK2                      1030
#define IDC_CHECK3                      1031
#define IDC_CHECK4                      1032
#define IDC_CHECK5                      1033
#define IDC_RADIO5                      1034
#define IDC_RADIO6                      1035
#define IDC_STATIC7                     1036
#define IDC_STATIC5                     1037
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_IMPORT                  40005
#define ID_FILE_EXPORT                  40006
#define ID_FILE_EXIT                    40007
#define ID_HELP_ABOUT                   40008
#define ID_EDIT_SELECTALL               40013
#define ID_EDIT_ADDSTRING               40023
#define ID_PASTESPECIAL_UNION           40026
#define ID_PASTESPECIAL_DIFFERENCE      40028
#define ID_LANGUAGE_ADD                 40030
#define ID_LANGUAGE_CHANGE              40031
#define ID_LANGUAGE_DELETE              40032
#define ID_EDIT_DELETE                  40038
#define ID_EDIT_FINDNEXTINVALID         40062
#define ID_PASTESPECIAL_INTERSECTION    40063
#define ID_EDIT_FINDNEXT                40065
#define ID_LANGUAGE_PREVIOUS            40068
#define ID_LANGUAGE_NEXT                40069
#define ID_EDIT_MOVEVALUESDOWN          40074
#define ID_EDIT_MOVEVALUESUP            40075
#define ID_EDIT_MOVESTRINGSUP           40076
#define ID_EDIT_MOVESTRINGSDOWN         40077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
